### ISSUE TITLE
Created Docker image

### ISSUE THREAD

**Issue by maskalix** [exolutionza/lilmail#4]
Hi, found this useful for someone.
This is based on the pull request with full mail address.

[https://hub.docker.com/r/maskalicz/lilmail](https://hub.docker.com/r/maskalicz/lilmail)

(Unofficial) release of Lilmail for Docker - based on https://github.com/exolutionza/lilmail/ 
(now pull request 'feat: Add option to allow full email as username')

compose file:
```
services:
  lilmail:
    image: maskalicz/lilmail:latest
    container_name: lilmail
    ports:
      - "3000:3000"
    restart: always
    environment:
      - CONFIG_FILE=/app/config.toml
    volumes:
      - ./config.toml:/app/config.toml
```

recommended config:
```
[server]
port = 3000
username_is_email = true

[imap]
server = "imap.your.tld"
port = 993
tls = true

[smtp]
server = "smtp.your.tld"
port = 587
use_starttls = true

[cache]
folder = "./cache"

[jwt]
secret = "your-secure-jwt-secret"

[encryption]
key = "your-32-character-encryption-key"

[ssl]
enabled = false
```
